### ISSUE TITLE
Error: No matching thread found

### ISSUE THREAD

**Issue by SamMackrill** [Friendly0Fire/GW2Clarity#49] opened 2023-12-13 09:53 UTC
**Describe the bug**
On start-up get error popup: No matching thread found
Clicking OK will then crash GW2 back to desktop

**To Reproduce**
1. Start GW2

**Expected behavior**
No popup, all runs

**Screenshots**
![image](https://github.com/Friendly0Fire/GW2Clarity/assets/84898/1ea872ce-79f7-4813-b8c4-08ec41c7b346)

**System configuration (please fill in):**
 - OS: [e.g. Windows 10] Win10
 - GPU: [e.g. GTX1080] GTX 1080
 - Chainloading, if any [e.g. arcdps -> GW2Radial -> GW2Hook] ?

**Notes**
Started happening after the Dec 12 patch - 155626

**Comment by knoxfighter** [comment] 2023-12-13 09:56
This issue is already resolved in the [current nightly](https://github.com/Friendly0Fire/GW2Clarity/actions/runs/7187300115). A release will be added in the near future.

**Comment by SamMackrill** [comment] 2023-12-13 10:00
Confirming nightly build fixes the issue, thanks!

**Comment by Lesbionic** [comment] 2024-01-31 06:14
> This issue is already resolved in the [current nightly](https://github.com/Friendly0Fire/GW2Clarity/actions/runs/7187300115). A release will be created in the near future.

I'm having the same issue but I have no idea how to download/use this.  Could you please tell me what to do?

Sorry I'm absolutely useless in this platform.

**Comment by plopek** [comment] 2024-03-13 19:53
Nightly build already expired. Will there be any updates regarding this issue?

**Comment by Friendly0Fire** [comment] 2024-03-14 00:18
Given that I have a regular 9-5 job, you can expect updates when I find free time, so possibly over the weekend. I don't know what broke or why it broke, I haven't even logged into the game today.

**Comment by dexteerz** [comment] 2024-03-26 05:43
![image](https://github.com/Friendly0Fire/GW2Clarity/assets/11621793/f719feb5-2326-428d-ac45-59bf8ae3997d)
Good evening, I'm having the same problem, and with an error warning from NVIDIA.

System configuration (please fill in):

OS: Win 11
GPU: RTX 2060
Chainloading: ARCDPS

**Comment by langgregor** [comment] 2024-09-19 11:48
![image](https://github.com/user-attachments/assets/eb3a240f-01cd-4770-a9a9-fc4d42c3ccc6)

Hi, Issue apparently still persists. I got rid of the Nvidia Ansel by deactivating Photo Mode in the GeForce Experience Overlay.

System configuration (please fill in):

OS: Win 11
GPU: RTX 4070 Super
Chainloading: ARCDPS, gw2radial

**Comment by Friendly0Fire** [comment] 2024-09-20 03:32
Duplicate of #60, please see that issue for the resolution.

**Closed by Friendly0Fire** 2024-09-20 03:32 UTC
